// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ForwardingRule
    {
        /// <summary>
        /// Initializes a new instance of the ForwardingRule class.
        /// </summary>
        public ForwardingRule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ForwardingRule class.
        /// </summary>
        /// <param name="field">Possible values include: 'From', 'To',
        /// 'Subject'</param>
        /// <param name="operatorProperty">Possible values include: 'EndsWith',
        /// 'StartsWith', 'Contains'</param>
        public ForwardingRule(string field = default(string), string operatorProperty = default(string), string value = default(string), string forwardTo = default(string))
        {
            Field = field;
            OperatorProperty = operatorProperty;
            Value = value;
            ForwardTo = forwardTo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'From', 'To', 'Subject'
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'EndsWith', 'StartsWith',
        /// 'Contains'
        /// </summary>
        [JsonProperty(PropertyName = "operator")]
        public string OperatorProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "forwardTo")]
        public string ForwardTo { get; set; }

    }
}
