// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MailosaurError
    {
        /// <summary>
        /// Initializes a new instance of the MailosaurError class.
        /// </summary>
        public MailosaurError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MailosaurError class.
        /// </summary>
        /// <param name="type">Possible values include: 'None',
        /// 'ValidationError', 'AuthenticationError', 'PermissionDeniedError',
        /// 'ResourceNotFoundError'</param>
        public MailosaurError(string type = default(string), IDictionary<string, string> messages = default(IDictionary<string, string>), object model = default(object))
        {
            Type = type;
            Messages = messages;
            Model = model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'None', 'ValidationError',
        /// 'AuthenticationError', 'PermissionDeniedError',
        /// 'ResourceNotFoundError'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "messages")]
        public IDictionary<string, string> Messages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public object Model { get; set; }

    }
}
