// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MessageContent
    {
        /// <summary>
        /// Initializes a new instance of the MessageContent class.
        /// </summary>
        public MessageContent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageContent class.
        /// </summary>
        public MessageContent(IList<Link> links = default(IList<Link>), IList<Image> images = default(IList<Image>), string body = default(string))
        {
            Links = links;
            Images = images;
            Body = body;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public IList<Link> Links { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<Image> Images { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

    }
}
