// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MessageHeader
    {
        /// <summary>
        /// Initializes a new instance of the MessageHeader class.
        /// </summary>
        public MessageHeader()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageHeader class.
        /// </summary>
        /// <param name="field">Header key.</param>
        /// <param name="value">Header value.</param>
        public MessageHeader(string field = default(string), string value = default(string))
        {
            Field = field;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets header key.
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// Gets or sets header value.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
