// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The result of a message listing request.
    /// </summary>
    public partial class MessageListResult
    {
        /// <summary>
        /// Initializes a new instance of the MessageListResult class.
        /// </summary>
        public MessageListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageListResult class.
        /// </summary>
        /// <param name="items">The individual summaries of each message
        /// forming the result. Summaries are returned sorted by received date,
        /// with the most recently-received messages appearing first.</param>
        public MessageListResult(IList<MessageSummary> items = default(IList<MessageSummary>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the individual summaries of each message forming the
        /// result. Summaries are returned sorted by received date, with the
        /// most recently-received messages appearing first.
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<MessageSummary> Items { get; set; }

    }
}
