// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MessageAddress
    {
        /// <summary>
        /// Initializes a new instance of the MessageAddress class.
        /// </summary>
        public MessageAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageAddress class.
        /// </summary>
        /// <param name="name">Display name, if one is specified.</param>
        /// <param name="email">Email address (applicable to email
        /// messages).</param>
        /// <param name="phone">Phone number (applicable to SMS
        /// messages).</param>
        public MessageAddress(string name = default(string), string email = default(string), string phone = default(string))
        {
            Name = name;
            Email = email;
            Phone = phone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets display name, if one is specified.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets email address (applicable to email messages).
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets phone number (applicable to SMS messages).
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

    }
}
