// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Advanced use case content related to the message.
    /// </summary>
    public partial class Metadata
    {
        /// <summary>
        /// Initializes a new instance of the Metadata class.
        /// </summary>
        public Metadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Metadata class.
        /// </summary>
        /// <param name="headers">Email headers.</param>
        public Metadata(IList<MessageHeader> headers = default(IList<MessageHeader>))
        {
            Headers = headers;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets email headers.
        /// </summary>
        [JsonProperty(PropertyName = "headers")]
        public IList<MessageHeader> Headers { get; set; }

    }
}
