// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SearchCriteria
    {
        /// <summary>
        /// Initializes a new instance of the SearchCriteria class.
        /// </summary>
        public SearchCriteria()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchCriteria class.
        /// </summary>
        /// <param name="sentTo">The full email address to which the target
        /// email was sent.</param>
        /// <param name="subject">The value to seek within the target email's
        /// subject line.</param>
        /// <param name="body">The value to seek within the target email's HTML
        /// or text body.</param>
        public SearchCriteria(string sentTo = default(string), string subject = default(string), string body = default(string))
        {
            SentTo = sentTo;
            Subject = subject;
            Body = body;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the full email address to which the target email was
        /// sent.
        /// </summary>
        [JsonProperty(PropertyName = "sentTo")]
        public string SentTo { get; set; }

        /// <summary>
        /// Gets or sets the value to seek within the target email's subject
        /// line.
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or sets the value to seek within the target email's HTML or
        /// text body.
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

    }
}
