// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ServerCreateOptions
    {
        /// <summary>
        /// Initializes a new instance of the ServerCreateOptions class.
        /// </summary>
        public ServerCreateOptions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServerCreateOptions class.
        /// </summary>
        /// <param name="name">A name used to identify the server.</param>
        public ServerCreateOptions(string name = default(string))
        {
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a name used to identify the server.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
