// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The result of a server listing request.
    /// </summary>
    public partial class ServerListResult
    {
        /// <summary>
        /// Initializes a new instance of the ServerListResult class.
        /// </summary>
        public ServerListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServerListResult class.
        /// </summary>
        /// <param name="items">The individual servers forming the result.
        /// Servers are returned sorted by creation date, with the most
        /// recently-created server appearing first.</param>
        public ServerListResult(IList<Server> items = default(IList<Server>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the individual servers forming the result. Servers are
        /// returned sorted by creation date, with the most recently-created
        /// server appearing first.
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<Server> Items { get; set; }

    }
}
