// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SpamAssassinRule
    {
        /// <summary>
        /// Initializes a new instance of the SpamAssassinRule class.
        /// </summary>
        public SpamAssassinRule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpamAssassinRule class.
        /// </summary>
        public SpamAssassinRule(double? score = default(double?), string rule = default(string), string description = default(string))
        {
            Score = score;
            Rule = rule;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rule")]
        public string Rule { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
