// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SpamCheckResult
    {
        /// <summary>
        /// Initializes a new instance of the SpamCheckResult class.
        /// </summary>
        public SpamCheckResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpamCheckResult class.
        /// </summary>
        public SpamCheckResult(IList<SpamAssassinRule> spamAssassin = default(IList<SpamAssassinRule>), System.Guid? emailId = default(System.Guid?), System.Guid? accountId = default(System.Guid?), double? score = default(double?))
        {
            SpamAssassin = spamAssassin;
            EmailId = emailId;
            AccountId = accountId;
            Score = score;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spamAssassin")]
        public IList<SpamAssassinRule> SpamAssassin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailId")]
        public System.Guid? EmailId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public System.Guid? AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

    }
}
