// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SpamFilterResults
    {
        /// <summary>
        /// Initializes a new instance of the SpamFilterResults class.
        /// </summary>
        public SpamFilterResults()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpamFilterResults class.
        /// </summary>
        public SpamFilterResults(IList<SpamAssassinRule> spamAssassin = default(IList<SpamAssassinRule>))
        {
            SpamAssassin = spamAssassin;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spamAssassin")]
        public IList<SpamAssassinRule> SpamAssassin { get; set; }

    }
}
