// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Mailosaur.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SpamAnalysisResult
    {
        /// <summary>
        /// Initializes a new instance of the SpamAnalysisResult class.
        /// </summary>
        public SpamAnalysisResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpamAnalysisResult class.
        /// </summary>
        public SpamAnalysisResult(SpamFilterResults spamFilterResults = default(SpamFilterResults), double? score = default(double?))
        {
            SpamFilterResults = spamFilterResults;
            Score = score;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spamFilterResults")]
        public SpamFilterResults SpamFilterResults { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

    }
}
